### ISSUE TITLE
Is is possible to "split" a string?

### ISSUE THREAD

**Issue by drozzy** [imatix/gsl#101]
If my template contains a few items like this:

    <event>ab</event>

is it possible to get "a" and "b" individually out of it?

I am trying to avoid writing:

    <event>
      <item>a</item>
      <item>b</item>
    </event>

Thank you very much!

**Comment by hintjens** [comment]
You can use string.substr.

**Comment by drozzy** [comment]
Thanks, I've actually decided to use items.

But your solution would only work for fixed-length strings... If I had arbitrary string, say "abasdfa" - I want to get each letter out of it individually. BUT never-mind, as I've already did it a different way.
