### ISSUE TITLE
directory.open fails on windows 7

### ISSUE THREAD

**Issue by drozzy** [imatix/gsl#103]
If I try to invoke `directory.open` in windows (through git-bash command window), I get a very generic crash/error:

`Fatal error in application - aborted
Abort. Compile with SMT_DETECT for more info`.

Here is the windows dump:

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: gsl.exe
  Application Version:  4.1.0.1
  Application Timestamp:    535a440f
  Fault Module Name:    gsl.exe
  Fault Module Version: 4.1.0.1
  Fault Module Timestamp:   535a440f
  Exception Code:   40000015
  Exception Offset: 00061c12
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: 6939
  Additional Information 2: 6939339b9a0e782d21c6f23fdc14279d
  Additional Information 3: bba4
  Additional Information 4: bba4a1ea307ad9bca6c913b55c2e196e

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by evoskuil** [comment]
I just built and ran latest Release|x64 in VS2011 express on Windows 7. The following commands complete as expected:
```
if (!defined(directory.open("c:\\", error_text)))
    echo "$(error_text)"
endif
```
```
if (!defined(directory.open("c:\\not-found", error_text)))
    echo "$(error_text)"
endif
```
```
'c:\not-found' is empty
```

**Comment by drozzy** [comment]
Hm... must be something very specific to my machine then... I'll try again on a different pc
