### ISSUE TITLE
Help: how to split xml file in two

### ISSUE THREAD

**Issue by drozzy** [imatix/gsl#104]
Update: My example is here https://bitbucket.org/drozdyuk/fruits-sample/src

I am trying to create a "static" site (this is following the tutorial in the guide). Here is what xml looks like right now.

    <?xml version = "1.0" ?>

    <site 
      copyright = "Copyright &#169; Local Grocer"
      script = "sitegen.gsl"
      >

    <page name = "home" />
    <page name = "videos" />
    <page name = "bio" />

    <link icon="facebook" name="Facebook" url = "http://www.facebook.com/blah" />
    <link icon="camera" name="Youtube" url = "http://www.youtube.com/user/blah" />
    <link icon="film" name="Picasa" url = "http://picasaweb.google.com/323423" />
    <link icon="twitter" name="Twiter" url = "http://twitter.com/blah" />

    </site>

However, I want to take out the "links" into a separate xml file, and I can't figure out how! I tried everything from "xml to site from "links.xml"" to "xml . load_file(links.xml)" --- the closest I came to a solution was only the FIRST link was showing up in the final markup.... Am I missing something?

For the life of me I can't figure it out, and don't know where to ask for help (stackoverflow gsl tag is not what I need).

**Comment by hintjens** [comment]
Post your example GSL and XML code somewhere (a gist) and someone may help
you.

**Comment by drozzy** [comment]
Ok, I've bundled it up as a small git project here:
https://bitbucket.org/drozdyuk/fruits-sample/src

The two files of interest are sitegen.gsl - where I try to load the "links.xml":
https://bitbucket.org/drozdyuk/fruits-sample/src/07efb4910bde9bf080117e6382fdf921780610d5/sitegen.gsl?at=master&fileviewer=file-view-default

and the `template.gsl` where I iterate through "links" and try to display them:
https://bitbucket.org/drozdyuk/fruits-sample/src/07efb4910bde9bf080117e6382fdf921780610d5/template.gsl?at=master&fileviewer=file-view-default

Nothing shows up... the links are not even in the root.xml dump.

**Comment by drozzy** [comment]
I've asked this on stackoverflow:
http://stackoverflow.com/questions/32593058/how-to-include-another-xml-file

So please answer over there!

Not sure why there wasn't a tag for gsl yet! Seems like a nifty tool.

**Comment by hintjens** [comment]
I answered on the StackExchange site.
