### ISSUE TITLE
Problem: src/* files licenses says GPL-2+, but COPYING says GPL-3+

### ISSUE THREAD

**Issue by bluca** [imatix/gsl#125]
@hintjens - shall we make it consistent? If so, to GPL-3+ ?

**Comment by hintjens** [comment]
Yes, that is a good solution.

**Comment by KrishnaPG** [comment]
Quick question on this line. May be answered elsewhere, but just to confirm: the code generated by this tool - can be it used in some other license (say commercial or MIT etc.), or would it be covered by GPL?

Usually GPL does not cover the output of a program and IMO the output / code generated by this tool is free to be licensed under any license. But just want to reconfirm with the owners of this tool, before looking into it deep.

**Comment by hintjens** [comment]
The license of the generated code is up to the user (or whomever writes the
templates). By default it's proprietary default copyright, i.e. you
generate code, that's your code and you own it.

**Comment by bluca** [comment]
What about adding a note about that in the readme to avoid any confusion? Or maybe even an explicit exception in the COPYING license file to make lawyers happy?
