### ISSUE TITLE
Problem: regexp.match broken on ARM64

### ISSUE THREAD

**Issue by bluca** [imatix/gsl#131]
Testing on a Raspberry PI 3 running Fedora 24 (aarch64 kernel and aarch64 userspace) the following snippet:

```
.if !regexp.match ("match", "match")
.echo "wrong"
.endif
```

Prints on the PI3:

```
$ ./gsl test.gsl
GSL/4.1c Copyright (c) 1996-2016 iMatix Corporation
gsl/4 I: Processing test.gsl...
gsl/4 M: wrong
```

While on X86:

```
$ gsl test.gsl 
GSL/4.1c Copyright (c) 1996-2016 iMatix Corporation
gsl/4 I: Processing test.gsl...
```

**Comment by bluca** [comment]
The problem seems to be in src/ggcode.c evaluate_arithmetic_operator(), OP_NOT case of the switch.

When value.n is -1, the following code:

```
(double) ! (Bool) tcb-> result_node-> op2-> value. n;
```

On x86 results in 0, on arm64 results in 1.

So the test code really is:

```
.if ! -1
.echo "wrong"
.endif
```

It's only a problem with negative numbers, negating 0 and positive integers behave as expected. I would guess rounding problem. Will keep looking.

**Comment by jschultz** [comment]
A reasonable hypothesis might be that the code makes an incorrect assumption about the word width. Have you tried with amd64?

Cheers, Jonathan

---- On Tue, 30 Aug 2016 23:22:24 +0000 Luca Boccassi  wrote ----

**Comment by bluca** [comment]
Yes, amd64 is fine, I see that on arm64 and armhf, which I think have different word width. That's why I assumed that the problem is the casting to double and back to integer.

@hintjens - I've checked the git log but unfortunately that line was untouched since the first commit. Do you happen to remember why the cast to double and back to int was necessary?
https://github.com/imatix/gsl/blob/master/src/ggcode.c#L4082

**Comment by hintjens** [comment]
From vague memory the casts were to force the precision of the calculation,
and then the result.

**Comment by bluca** [comment]
Thanks. I'll double check that without the cast to double the problem goes away, and then I'll try to come up with a solution that still forces the precision but works on arm.

**Comment by bluca** [comment]
After some more triaging it turns out it's not the cast to double, it's the cast to bool that breaks it. I'll dig deeper tomorrow.

**Comment by bluca** [comment]
So I think we stumbled upon some nice undefined behaviour here.

Bool is typedef'd as unsigned short in prelude.h:

```typedef unsigned short  Bool;```

The operation casts value.n, a double, to Bool (ie: unsigned short), negates it, and then casts back to double:

```
tcb-> result_node-> value. n
                    = (double) ! (Bool) tcb-> result_node-> op2-> value. n;
```

The problem is that casting a negative float/double to unsigned int is undefined behaviour, as far as I can see. Relevant section of the standard:

http://c0x.coding-guidelines.com/6.3.1.4.html

I would propose to remove the explicit casts. The result of a logical and/or/not is always an int of value 0 or 1, which can be represented just fine as flat/double, and it is evaluated by comparing the variable to 0 in all cases, so avoiding an explicit cast should be fine in all situations.
