### ISSUE TITLE
Tagging stable versions

### ISSUE THREAD

**Issue by fnchooft** [imatix/gsl#134]
Good Evening, Thanks for the great tool.
Could we get tags for stable versions?

Fabian

**Comment by jschultz** [comment]
Glad you like it!

GSL has been largely stable for many years and as far as I am aware any 
recent activity is largely bugfixes.

Cheers,
Jonathan

**Comment by fnchooft** [comment]
Hi Jonathan, thanks for responding so quickly.
I was more thinking about build-systems or dependencies in general.
In that case it would be helpful to have a tag instead of a hash to checkout a specific version.

Like for instance in zproject's project.xml:
`<use project = "zyre" min_major= "1" min_minor = "1" min_patch = "0" />`

Currently the version is based on src/version.h - One could use a version.sh.in file (automake style) but that would complicate the compilation.

Kind regards,

Fabian

**Comment by jschultz** [comment]
Sorry I'm afraid I don't know much about this stuff. Since Pieter's 
death I'm not sure who is in charge here, so maybe you'll just need to 
fork the project if it's important to have stable releases.

Cheers,
Jonathan

**Comment by bluca** [comment]
There's no need to fork, @evoskuil has admin rights on the repository

**Comment by fnchooft** [comment]
First of all my condolences, primarily for the family of Pieter. Secondly for the people who had the pleasure of working with him closely.
He will be missed and leaves an impressive legacy

**Comment by evoskuil** [comment]
@bluca, yes - it appears so. Sorry I've been missing notices here, it took me a while to notice this change.

Hi @fnchooft - The [version file](https://github.com/imatix/gsl/blob/master/src/version.h#L47) indicates 4.1c so I went with [v4.1.3](https://github.com/imatix/gsl/releases/tag/v4.1.3) (using the zeromq/czmq format).

**Comment by bluca** [comment]
Thank you! Would be nice if the version header could be changed to match, and to upload a "make dist" tarball to the github release

**Comment by evoskuil** [comment]
Okay, do you mean [this line](https://github.com/imatix/gsl/blob/master/src/version.h#L46)? I don't know what the "c" implies in 4.1c - I assume it implies a third minor version.

**Comment by bluca** [comment]
yeah both VERSION and PRODUCT - I think so it was a minor version

**Comment by evoskuil** [comment]
```
#define VERSION         "4.1.3"
#define PRODUCT         "GSL/4.1.3"
```
?

**Comment by bluca** [comment]
Before it was GSL/4.1b/github: 10a9359cc5b9d00f43abf21bc077460f5021904d
So it looks indeed like a minor version. Using 3 digits is simpler IMHO, so what you have there looks good to me

**Comment by evoskuil** [comment]
All set, tag replaced. I'll try and get to the tarball soon.
