### ISSUE TITLE
Licensing of generated code

### ISSUE THREAD

**Issue by machinekoder** [imatix/gsl#138]
Are there any restrictions on the license of the code generated by the GSL? GSL itself is licensed under the terms of the GPLv3. However, can I used this tool generate source code for closed source projects given that I write the GSL templates and scripts myself?

If I understand it correctly the GSL is technically a compiler - then it should be possible. Can anyone clarify this?

Also, I think it would be good to add a paragraph about the licensing of generated source to the README.

**Comment by bluca** [comment]
The intention of Pieter was clearly expressed in this comment https://github.com/imatix/gsl/issues/125#issuecomment-242890373

```
The license of the generated code is up to the user (or whomever writes the
templates). By default it's proprietary default copyright, i.e. you
generate code, that's your code and you own it.
```

@evoskuil do you agree with this as well? I also think that being explicit with the licensing question is better to cast away any possible doubt

**Comment by evoskuil** [comment]
Yes, the generated code should be the property of the person who wrote the GSL to generate it.

**Comment by bluca** [comment]
@evoskuil perfect, opened PR #139 to clarify in the README
