### ISSUE TITLE
Accessing XML comments

### ISSUE THREAD

**Issue by machinekoder** [imatix/gsl#143]
Is there a way to access XML comments?

Such as for example:

```xml
<!--
D-Bus interface for a digital output.
-->
<interface name="at.alex.digital.outout">
</interface>
```

**Comment by jschultz** [comment]
No, comments are ignored by the XML parser.

It wouldn't be a huge job to implement in the parser, but would require 
some care inside GSL so as not to break existing scripts.

**Comment by machinekoder** [comment]
Okay, thanks. I create Python script that uses a regex to copy the comments inside the next XML elements.
