### ISSUE TITLE
Travis CI and OBS packaging should be enabled for GSL repository

### ISSUE THREAD

**Issue by jimklimov** [imatix/gsl#154]
Following the merge of #152, @evoskuil or somebody else with admin access to the github repository should log in to https://travis-ci.org with their github account, scan accessible repositories and pull the lever for `imatix/gsl`, so the next commits into any branch (including PRs) that happen after this, are CI-tested. Usually the setup of web-hooks etc. should happen automatically; if not - follow Travis docs to connect CI to repo (usually only needed in paranoid setups with lowered permissions by default).

**Comment by bluca** [comment]
Would be nice to also enable OBS builds, as right now I have to manually kick the service every now and then.

**Comment by evoskuil** [comment]
I don't have the necessary permission. According to GitHub, I am a member, and @hintjens was the only person with higher level permission (owner). Personally I think it would be best to either migrate the project to [zeromq](https://github.com/zeromq) or to create an independent repository for it.

**Comment by bluca** [comment]
If we can migrate without owner permission let's do that. Otherwise we can ask Ewen McNeill as he might have permissions/passwords, since he was handling a lot of iMatix related stuff from the mailing list

**Comment by bluca** [comment]
@evoskuil given you are in the core maintainer group, coulud you please enable 2FA on Github?

**Comment by evoskuil** [comment]
You could migrate into a new zeromq repository by cloning locally and pushing it up, instead of using GitHub forking. That will preserve the history but not give people the impression that it isn't the "main" repository. Then we can update this repository to direct people to the new location.

**Comment by evoskuil** [comment]
Even with permissions to this site, I think it would be better for the project to be associated with zeromq, and it should be easier to manage as well.

**Comment by bluca** [comment]
There's been a few changes - what about tagging a last 4.1.4 release here before moving?

**Comment by evoskuil** [comment]
https://github.com/imatix/gsl/pull/155

**Comment by bluca** [comment]
Great, thanks!

**Comment by evoskuil** [comment]
Tagged: https://github.com/imatix/gsl/releases/tag/v4.1.4

**Comment by bluca** [comment]
So Ewen answered back and he doesn't have access either.

I've added the repo to the ZeroMQ org: https://github.com/zeromq/gsl and I've added both of you as admins.

@evoskuil can you edit the short description in https://github.com/imatix/gsl ? If so you could write that the development head has moved, this way we leave the git history as-is.

**Comment by bluca** [comment]
Also I've enabled both Travis and OBS hooks in the new repo, so we can close this now.
