### ISSUE TITLE
Prebuild Binaries

### ISSUE THREAD

**Issue by metadings** [imatix/gsl#29]
I'm not a first class C citizen, but I think it's really hard to compile GSL. First I thought it's as easy as "just use a UNIX box and do make". Yes, I'm "the guy who loves his Windows box", but I used an ubuntu to try it; it is not that "just" easy. Also with MSVC (my oldest Version is 10.0 / 2010 express) I just don't get it compiled. A hell of batch files are looking for VC98 compilers, deprecated options etc. With the current compiler it doesn't get the prelude.h and if I'm inserting the include hard into gsl.c I get a ton of new problems.

I just wanted to try GSL. After reading ZeroMQ The Guide, having an eye on the RFCs, and actually being impressed how simple all that looks (even in C), and how simple all that works (bound to c#) - I'm now trying to "get into" GSL.
But now I ended up in wasting hours of studying batch files, C compilers, arguments, linking problems and incompatible makefiles/project files and whatever.
Can you _please_ provide downloadable binaries (Win32/UNIX x86/amd64)?

**Comment by drozzy** [comment]
So does one need "nuget" to get a binary of this? Is it possible to get an "exe" file? Like in @KubaO  repo: https://github.com/KubaO/gsl/releases

**Comment by evoskuil** [comment]
See link above, which points [here](https://github.com/imatix/gsl/releases).

**Comment by drozzy** [comment]
O_O how did I miss that. Thanks!
