### ISSUE TITLE
Problem: GSL shouldn't output trailing whitespace at the end of an output line

### ISSUE THREAD

**Issue by jemc** [imatix/gsl#54]
Currently I can see no feasible way to output a block of multiple lines of text in a way that does not add trailing whitespace to all lines to match the length of the longest line.

I understand that many usages rely on having this trailing whitespace added, but In the interest of not having useless trailing whitespace all over the generated code (think comment blocks), it would be nice to have a way to opt out of that behavior.

Is there some formatting option or workaround already that I'm not aware of?

**Comment by bluca** [comment]
I gave a shot at fixing this issue, as it was annoying me a great deal :-)

https://github.com/imatix/gsl/pull/146
