### ISSUE TITLE
Problem: fatal error.

### ISSUE THREAD

**Issue by evoskuil** [imatix/gsl#69]
Getting this on [Travis](https://travis-ci.org/libbitcoin/libbitcoin-build#L115) and locally (Ubuntu). I reverted the [most recent commit](https://github.com/imatix/gsl/commit/86872fd2dce323af928d78fcb9cc88e414722802) locally and it's OK.
```
$ gsl -q generate.xml
Fatal error in application - aborted
Abort.  Compile with SMT_DETECT for more info.
Aborted (core dumped)
```

**Comment by jschultz** [comment]
Hi Eric,

Yes you are quite right. That commit was only supposed to go to my fork.
I am the master of messing up github repositories.

Cheers,
Jonathan

**Comment by evoskuil** [comment]
@jschultz No worries, SmartGit keeps me sane.

**Comment by evoskuil** [comment]
Resolved by https://github.com/imatix/gsl/commit/89c6b0659a35ae05664073e59137de133ff189ed
