### ISSUE TITLE
question: can I use GSL to generate Google API interfaces for Rust ?

### ISSUE THREAD

**Issue by Byron** [imatix/gsl#70]
Hi,

First of all sorry for posting a question here, but I thought chances for an answer are better here than on Stackoverflow.

As I am learning Rust currently, I decided to implement a commandline youtube uploader. To do that, one will need access to the Youtube Web API. When looking at the google API implementation for Go, I realised that it is nearly entirely generated. The generator is written in Go, reading structured data in Json format.

Even though I am implementing the first sketch manually, I want to go ahead and generate all the rest, based on the experiences I made by hand.

Now the question: If you are looking at the [API description](https://github.com/google/google-api-go-client/blob/master/youtube/v3/youtube-api.json), do you think (if converted to XML), GSL will be the tool to generate valid Rust ? I believe it *should* be possible from what I have read so far, but I want to be sure.

Generally, besides traversing the XML tree, I will have to map names (like 'boolean' to 'bool'), and possibly access XML structures by name, as parts of the XML tree softly reference each other. The name-mapping part should be doable using functions/macros, but I am not entirely sure about XML access by name (which is stored in a variable).

If you give me a thumbs up, I will be happy to dive into GSL, as I have been wanting to use it for quite a while now ! A code generator is missing in my tool-set, and I totally see the point when implementing protocols and basically anything that can be described by structured data.

Thank you !

**Comment by hintjens** [comment]
:+1:

**Comment by Byron** [comment]
Great to hear ! Also I didn't expect anything else really :).
In case I will encounter any roadblocks, I will post them on Stackoverflow. The `gsl` tag is taken already, maybe I will send a link to you by e-mail then.
Impressive streak by the way - am I the only one who sees pacman there ?

![screen shot 2015-02-28 at 18 02 34](https://cloud.githubusercontent.com/assets/63622/6427031/1cfd2b00-bf74-11e4-86f8-13e6e045537b.png)

**Comment by hintjens** [comment]
Wow, you're right! :)
