### ISSUE TITLE
problem: directory_open() always strips last path segment

### ISSUE THREAD

**Issue by evoskuil** [imatix/gsl#76]
This is called after formulating the proper directory.

```c
curpath = strip_file_name (pathname);
```
Given that the function is designed to accept a directory and not a file name, this always produces an incorrect result.

https://github.com/imatix/gsl/blob/master/src/ggfile.c#L1286

**Comment by jschultz** [comment]
What is the difference between a directory and a file name?

**Comment by evoskuil** [comment]
In this context there is none. The value passed into directory_open() is *always* stripped of its last segment.

**Comment by jschultz** [comment]
That does raise the question of how (or if?) it ever worked, and how it
appears still to work under Linux. The sfl library has been stable for
more than 10 years and has been used in many applications besides gsl.

**Comment by evoskuil** [comment]
That is an interesting question.

**Comment by evoskuil** [comment]
Possibly because the stripped result is not actually used anywhere.
