### ISSUE TITLE
Missing semi-colon in generated code.

### ISSUE THREAD

**Issue by oranjuice** [imatix/gsl#80]
Here is where it's missing: https://github.com/oranjuice/monero-0mq/blob/master/src/wap_proto.c#L602

The entire project with the xml protocol files are in: https://github.com/oranjuice/monero-0mq/tree/master/src

It uses zproto, and I'm not sure what was responsible for this.

**Comment by hintjens** [comment]
Just to provide background, these files are generated from zproto, and the
original GSL script definitely does have a semi-colon there.

@oranjuice, could you make sure you're using the latest zproto?

**Comment by oranjuice** [comment]
Sorry. I just updated it and it compiles fine.
