### ISSUE TITLE
Justification question

### ISSUE THREAD

**Issue by saleyn** [imatix/gsl#93]
Suppose I have an XML block with enumerated values of different lengths:
```
$ cat enum.xml
<code script="enum.gsl">
    <enum name="fruit" script="enum.gsl">
        <value code="1" val="orange"/>
        <value code="200" val="kiwi"/>
    </enum>
</code>
```
And I want to generate aligned code:
```
enum class fruit {
    orange =   1,
    kiwi   = 200
};
```
Is there a way to enforce this proper alignment in the generated code without manually having to pad the values?

**Comment by hintjens** [comment]
GSL will treat 2 or more spaces as 'elastic' when it expands variables.
This is usually what you want for alignment.

**Comment by jschultz** [comment]
See under the heading 'Shuffle' in gsldoc.txt

**Comment by saleyn** [comment]
I am having a little hard time understanding the example under "Shuffle" in the README.md (also I can't find the gsldoc.txt file in this repository, did you mean the README.md file?).  In order to produce the output above I put together this code:
```
.for enum
    enum class $(name) {
.   for value
        $(.val)  = $(.code)$(!last() ?? ',')
.   endfor
    };
.endfor
```
I get:
```
    enum class fruit {
        orange   = 1,
        kiwi     = 200
    };
```
However there are two issues here:
1. There are two spaces after the $(.val), since I want to use the "Shuffle", and I only want to have one space in the output of the longest entry "orange".
2. How do I right-justify the $(.code)?

**Comment by jschultz** [comment]
OK at some point markdown got adopted so README.md is correct.

Long story short is shuffle doesn't work by figuring out what the
longest string does, it works by using the column number of the next
item. So there is no easy way to have only one space following 'orange'.

Right-justification can be achieved using a format string. It's in
README.md.

**Comment by saleyn** [comment]
Sorry here when I refer to right justification I want similar functionality to shufile (to use the padding based on the longest value in the set of values) but to do right alignment. Is this doable?

**Comment by hintjens** [comment]
You can use a combination of shuffle, and printf formatting within the
value, check the doc for "printf".

**Comment by saleyn** [comment]
That's exactly what I am having trouble with. When not using shuffle I can do:
```
.   for value
        $(.val)  = $(.code%3d)$(!last() ?? ',')
.   endfor
```
which results in the desired output:
```
        orange   =   1,
        kiwi     = 200
```
However I don't want to hard-code the width (3), and don't see the way for it to be auto-calculated.
If I use that in combination with the shuffle, what would be the expression "inside the value"? The following doesn't seem to work:
```
.   for value
        $(.val)  = $($(.code%d)  $(!last() ?? ','))
.   endfor
```
I haven't used gsl before and trying to see if it could replace some of the home-grown template processor...

**Comment by hintjens** [comment]
This is silliness. I'm closing the issue.

**Comment by saleyn** [comment]
With all due respect to the maintainer it would be much more constructive if either documentation was more complete on this subject or your answer was illustrated with a one-liner example.  I wouldn't think that a simple comprehensive example was too much to ask for (even if this formatting issue seems silly and unworthy).
