### ISSUE TITLE
Switching between template/script modes

### ISSUE THREAD

**Issue by saleyn** [imatix/gsl#97]
It seems to me that it would be very useful to switch between template/script mode automatically depending on the use of function/macro keyword.

Presently the syntax forces you to write:
```
.template 0
function test1
  echo "test1"
endfunction

template 1
.macro test2
.  echo "test2"
.endmacro
endtemplate
.endtemplate
```

I propose to make a change so that the use of "macro" keyword in the script mode would automatically switch to template mode in the body of that macro (if not already in the template mode), and vice versa (use of "function" keyword would automatically switch to script mode in the body of the function if not already in the script mode):

```
.template 0
function test1  # already in script mode - not switching template mode
  echo "test1"
endfunction

macro test2     # in script mode - automatically switching to template mode
.  echo "test2"
endmacro        # returning back to script mode

endtemplate
```

I would've submitted a pull request as I thought this was a simple change, but frankly after looking at the source code for 20min, couldn't find a place where the template mode is being set when evaluating the function/macro. :(

**Comment by evoskuil** [comment]
+1

**Comment by jschultz** [comment]
This is already the case as far as I can tell.

With only one difference - the endmacro keyword has to be written
.endmacro - otherwise it looks like a template.

Jonathan

**Comment by saleyn** [comment]
You are right indeed. It's the '.' before endmacro that was throwing things off. Sorry for noise.
